### ISSUE TITLE
missing data file in 0.1.3 pip release - aikif.programs

### ISSUE THREAD

**Issue by acutesoftware** [acutesoftware/AIKIF#30]
problem is with cls_file_mapping.py referring to sub data folder not included in package - may need to move \data underneath \aikif so that it is installed - check for sizes first

>>> import aikif.programs
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python34\lib\site-packages\aikif\programs.py", line 11, in <module>
    import aikif.cls_file_mapping as mod_filemap
  File "C:\Python34\lib\site-packages\aikif\cls_file_mapping.py", line 21, in <m
odule>
    with open(file_type_file, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Python34\\lib\\site
-packages\\data\\ref\\ONTOLOGY_FILE_TYPE.txt'

**Comment by acutesoftware** [comment]
Fixed cls_file_mapping and uploaded 0.1.4
