### ISSUE TITLE
image_test fails on Ubuntu

### ISSUE THREAD

**Issue by acutesoftware** [acutesoftware/AIKIF#34]
Resolved this after a lot of stuffing around. Basically all tests pass on Windows and travis-CI but on a fresh install of Ubuntu 14.04 LTS Pillow failed tests.

Read the docs says:
http://pillow.readthedocs.org/installation.html 

sudo apt-get install python3-dev python3-setuptools

Prerequisites are installed on Ubuntu 14.04 LTS with:

$ sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk

Also tried (thanks to helpful folks at IRC python

apt-get build-dep

Finally worked in virtualenv only:

virtualenv -p /usr/bin/python3 venv
source venv/bin/activate
pip install Pillow

**Comment by acutesoftware** [comment]
======================================================================
ERROR: test_07_print_stats (test_toolbox_image_tools.TestClassImageTools)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 416, in _getdecoder
    decoder = getattr(core, decoder_name + "_decoder")
AttributeError: 'module' object has no attribute 'jpeg_decoder'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duncan/dev/src/python/AIKIF/tests/test_toolbox_image_tools.py", line 71, in test_07_print_stats
    cl.print_stats(i)
  File "/home/duncan/dev/src/python/AIKIF/aikif/toolbox/image_tools.py", line 102, in print_stats
    stat = ImageStat.Stat(img)
  File "/usr/local/lib/python3.4/dist-packages/PIL/ImageStat.py", line 36, in __init__
    self.h = image_or_list.histogram()
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 1246, in histogram
    self.load()
  File "/usr/local/lib/python3.4/dist-packages/PIL/ImageFile.py", line 203, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 420, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
OSError: decoder jpeg not available


As described in issue body, this is resolved when running in virtualenv

. ~/p von   <-- see dotfiles script

(venv)duncan@TREEBEARD-LINUX:~/dev/src/python/AIKIF/tests$ pip install Pillow
Collecting Pillow
Installing collected packages: Pillow
Successfully installed Pillow-2.9.0
(venv)duncan@TREEBEARD-LINUX:~/dev/src/python/AIKIF/tests$ python test_toolbox_image_tools.py
/usr/lib/python3.4/unittest/case.py:574: ResourceWarning: unclosed file <_io.BufferedReader name='/home/duncan/dev/src/python/AIKIF/doc/AIKIF-Overview.jpg'>
  testMethod()
./home/duncan/dev/src/python/AIKIF/tests/venv/local/lib/python3.4/site-packages/PIL/Image.py:1246: ResourceWarning: unclosed file <_io.BufferedReader name='/home/duncan/dev/src/python/AIKIF/doc/AIKIF-Overview.jpg'>
  self.load()
.Filename   : /home/duncan/dev/src/python/AIKIF/doc/AIKIF-Overview.jpg
Basename   : AIKIF-Overview.jpg
Path       : /home/duncan/dev/src/python/AIKIF/doc
Size       : 110659
Width      : 895
Height     : 570
Format     : JPEG
palette    : None
extrema    :  [(0, 255), (0, 255), (0, 255)]
count      :  [510150, 510150, 510150]
sum        :  [124456196.0, 124797169.0, 124982434.0]
sum2       :  [31192906918.0, 31346818279.0, 31448301230.0]
mean       :  [243.96000392041557, 244.62838184847593, 244.99153974321277]
median     :  [255, 255, 255]
rms        :  [247.27429887604933, 247.88359593207457, 248.28452388843945]
var        :  [1628.0953717925915, 1603.2319264122636, 1624.3502567588569]
stddev     :  [40.349663837417424, 40.04037869966097, 40.30322886269606]
GPS Lat    : None
GPS Long   : None
./home/duncan/dev/src/python/AIKIF/tests/venv/local/lib/python3.4/site-packages/PIL/Image.py:1557: ResourceWarning: unclosed file <_io.BufferedReader name='/home/duncan/dev/src/python/AIKIF/doc/AIKIF-Overview.jpg'>
  self.load()
get_img_hash: pixels= [(237, 237, 236), (233, 233, 233), (234, 234, 234), (232, 232, 232), (234, 234, 235), (234, 234, 234), (236, 236, 236), (239, 239, 239), (255, 255, 255), (235, 239, 244), (247, 249, 249), (252, 252, 251), (248, 248, 248), (250, 250, 248), (247, 247, 248), (249, 249, 248), (247, 248, 247), (246, 246, 246), (221, 227, 235), (238, 240, 241), (246, 245, 244), (240, 241, 240), (245, 246, 244), (241, 241, 241), (245, 245, 244), (241, 241, 240), (240, 240, 240), (255, 255, 255), (255, 255, 255), (253, 254, 253), (248, 248, 246), (255, 255, 255), (246, 246, 244), (254, 254, 253), (255, 255, 255), (255, 255, 255), (255, 255, 255), (255, 255, 255), (249, 249, 249), (239, 240, 239), (247, 247, 245), (242, 242, 242), (249, 249, 249), (246, 246, 246), (232, 232, 232), (255, 255, 255), (255, 255, 255), (251, 251, 251), (244, 244, 242), (252, 251, 250), (244, 243, 242), (251, 251, 251), (247, 247, 247), (231, 231, 230), (254, 254, 254), (253, 253, 253), (250, 251, 251), (241, 243, 243), (248, 249, 251), (241, 243, 243), (251, 251, 251), (251, 251, 250), (246, 246, 244), (232, 235, 240), (230, 233, 235), (239, 241, 241), (224, 230, 240), (216, 222, 230), (224, 231, 241), (240, 243, 244), (242, 243, 240), (238, 238, 239)]
./home/duncan/dev/src/python/AIKIF/tests/venv/local/lib/python3.4/site-packages/PIL/Image.py:1246: ResourceWarning: unclosed file <_io.BufferedReader name='/home/duncan/dev/src/python/AIKIF/doc/web-if-v02.jpg'>
  self.load()
..extrema    :  [(0, 255), (0, 255), (0, 255)]
count      :  [407252, 407252, 407252]
sum        :  [3875637.0, 10036578.0, 12348134.0]
sum2       :  [478505413.0, 1430454218.0, 2155115714.0]
mean       :  [9.516557315863396, 24.644637718169584, 30.320622120947228]
median     :  [0, 0, 0]
rms        :  [34.27771113788303, 59.26596612351612, 72.74508972653683]
var        :  [1084.3966177060374, 2905.0965722939336, 4372.50795352062]
stddev     :  [32.930177917922606, 53.898947784663974, 66.12494199256903]
.
----------------------------------------------------------------------
Ran 7 tests in 0.065s

OK
